/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing AccessTokenInfoResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessTokenInfoResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessTokenInfoResponse
        //private AccessTokenInfoResponse instance;

        public AccessTokenInfoResponseTests()
        {
            // TODO uncomment below to create an instance of AccessTokenInfoResponse
            //instance = new AccessTokenInfoResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessTokenInfoResponse
        /// </summary>
        [Fact]
        public void AccessTokenInfoResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessTokenInfoResponse
            //Assert.IsType<AccessTokenInfoResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'HubDomain'
        /// </summary>
        [Fact]
        public void HubDomainTest()
        {
            // TODO unit test for the property 'HubDomain'
        }
        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }
        /// <summary>
        /// Test the property 'ScopeToScopeGroupPks'
        /// </summary>
        [Fact]
        public void ScopeToScopeGroupPksTest()
        {
            // TODO unit test for the property 'ScopeToScopeGroupPks'
        }
        /// <summary>
        /// Test the property 'TrialScopes'
        /// </summary>
        [Fact]
        public void TrialScopesTest()
        {
            // TODO unit test for the property 'TrialScopes'
        }
        /// <summary>
        /// Test the property 'TrialScopeToScopeGroupPks'
        /// </summary>
        [Fact]
        public void TrialScopeToScopeGroupPksTest()
        {
            // TODO unit test for the property 'TrialScopeToScopeGroupPks'
        }
        /// <summary>
        /// Test the property 'HubId'
        /// </summary>
        [Fact]
        public void HubIdTest()
        {
            // TODO unit test for the property 'HubId'
        }
        /// <summary>
        /// Test the property 'AppId'
        /// </summary>
        [Fact]
        public void AppIdTest()
        {
            // TODO unit test for the property 'AppId'
        }
        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

    }

}
