/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing AccountingAppUrls
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountingAppUrlsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountingAppUrls
        //private AccountingAppUrls instance;

        public AccountingAppUrlsTests()
        {
            // TODO uncomment below to create an instance of AccountingAppUrls
            //instance = new AccountingAppUrls();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountingAppUrls
        /// </summary>
        [Fact]
        public void AccountingAppUrlsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountingAppUrls
            //Assert.IsType<AccountingAppUrls>(instance);
        }


        /// <summary>
        /// Test the property 'GetInvoiceUrl'
        /// </summary>
        [Fact]
        public void GetInvoiceUrlTest()
        {
            // TODO unit test for the property 'GetInvoiceUrl'
        }
        /// <summary>
        /// Test the property 'SearchCustomerUrl'
        /// </summary>
        [Fact]
        public void SearchCustomerUrlTest()
        {
            // TODO unit test for the property 'SearchCustomerUrl'
        }
        /// <summary>
        /// Test the property 'GetInvoicePdfUrl'
        /// </summary>
        [Fact]
        public void GetInvoicePdfUrlTest()
        {
            // TODO unit test for the property 'GetInvoicePdfUrl'
        }
        /// <summary>
        /// Test the property 'CustomerUrlTemplate'
        /// </summary>
        [Fact]
        public void CustomerUrlTemplateTest()
        {
            // TODO unit test for the property 'CustomerUrlTemplate'
        }
        /// <summary>
        /// Test the property 'ProductUrlTemplate'
        /// </summary>
        [Fact]
        public void ProductUrlTemplateTest()
        {
            // TODO unit test for the property 'ProductUrlTemplate'
        }
        /// <summary>
        /// Test the property 'InvoiceUrlTemplate'
        /// </summary>
        [Fact]
        public void InvoiceUrlTemplateTest()
        {
            // TODO unit test for the property 'InvoiceUrlTemplate'
        }
        /// <summary>
        /// Test the property 'CreateInvoiceUrl'
        /// </summary>
        [Fact]
        public void CreateInvoiceUrlTest()
        {
            // TODO unit test for the property 'CreateInvoiceUrl'
        }
        /// <summary>
        /// Test the property 'SearchInvoiceUrl'
        /// </summary>
        [Fact]
        public void SearchInvoiceUrlTest()
        {
            // TODO unit test for the property 'SearchInvoiceUrl'
        }
        /// <summary>
        /// Test the property 'SearchProductUrl'
        /// </summary>
        [Fact]
        public void SearchProductUrlTest()
        {
            // TODO unit test for the property 'SearchProductUrl'
        }
        /// <summary>
        /// Test the property 'GetTermsUrl'
        /// </summary>
        [Fact]
        public void GetTermsUrlTest()
        {
            // TODO unit test for the property 'GetTermsUrl'
        }
        /// <summary>
        /// Test the property 'CreateCustomerUrl'
        /// </summary>
        [Fact]
        public void CreateCustomerUrlTest()
        {
            // TODO unit test for the property 'CreateCustomerUrl'
        }
        /// <summary>
        /// Test the property 'SearchTaxUrl'
        /// </summary>
        [Fact]
        public void SearchTaxUrlTest()
        {
            // TODO unit test for the property 'SearchTaxUrl'
        }
        /// <summary>
        /// Test the property 'ExchangeRateUrl'
        /// </summary>
        [Fact]
        public void ExchangeRateUrlTest()
        {
            // TODO unit test for the property 'ExchangeRateUrl'
        }
        /// <summary>
        /// Test the property 'SearchUrl'
        /// </summary>
        [Fact]
        public void SearchUrlTest()
        {
            // TODO unit test for the property 'SearchUrl'
        }
        /// <summary>
        /// Test the property 'SearchCountUrl'
        /// </summary>
        [Fact]
        public void SearchCountUrlTest()
        {
            // TODO unit test for the property 'SearchCountUrl'
        }

    }

}
