/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Address
        //private Address instance;

        public AddressTests()
        {
            // TODO uncomment below to create an instance of Address
            //instance = new Address();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Address
        /// </summary>
        [Fact]
        public void AddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" Address
            //Assert.IsType<Address>(instance);
        }


        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CountrySubDivisionCode'
        /// </summary>
        [Fact]
        public void CountrySubDivisionCodeTest()
        {
            // TODO unit test for the property 'CountrySubDivisionCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }
        /// <summary>
        /// Test the property 'LineOne'
        /// </summary>
        [Fact]
        public void LineOneTest()
        {
            // TODO unit test for the property 'LineOne'
        }

    }

}
