/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing AssociationDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AssociationDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AssociationDefinition
        //private AssociationDefinition instance;

        public AssociationDefinitionTests()
        {
            // TODO uncomment below to create an instance of AssociationDefinition
            //instance = new AssociationDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AssociationDefinition
        /// </summary>
        [Fact]
        public void AssociationDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" AssociationDefinition
            //Assert.IsType<AssociationDefinition>(instance);
        }


        /// <summary>
        /// Test the property 'FromObjectTypeId'
        /// </summary>
        [Fact]
        public void FromObjectTypeIdTest()
        {
            // TODO unit test for the property 'FromObjectTypeId'
        }
        /// <summary>
        /// Test the property 'ToObjectTypeId'
        /// </summary>
        [Fact]
        public void ToObjectTypeIdTest()
        {
            // TODO unit test for the property 'ToObjectTypeId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
