/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing ContactsNextPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContactsNextPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContactsNextPage
        //private ContactsNextPage instance;

        public ContactsNextPageTests()
        {
            // TODO uncomment below to create an instance of ContactsNextPage
            //instance = new ContactsNextPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContactsNextPage
        /// </summary>
        [Fact]
        public void ContactsNextPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContactsNextPage
            //Assert.IsType<ContactsNextPage>(instance);
        }


        /// <summary>
        /// Test the property 'After'
        /// </summary>
        [Fact]
        public void AfterTest()
        {
            // TODO unit test for the property 'After'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Fact]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

    }

}
