/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerSearchResponseExternal
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerSearchResponseExternalTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerSearchResponseExternal
        //private CustomerSearchResponseExternal instance;

        public CustomerSearchResponseExternalTests()
        {
            // TODO uncomment below to create an instance of CustomerSearchResponseExternal
            //instance = new CustomerSearchResponseExternal();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerSearchResponseExternal
        /// </summary>
        [Fact]
        public void CustomerSearchResponseExternalInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerSearchResponseExternal
            //Assert.IsType<CustomerSearchResponseExternal>(instance);
        }


        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Fact]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'Customers'
        /// </summary>
        [Fact]
        public void CustomersTest()
        {
            // TODO unit test for the property 'Customers'
        }

    }

}
