/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing DealsPaging
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DealsPagingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DealsPaging
        //private DealsPaging instance;

        public DealsPagingTests()
        {
            // TODO uncomment below to create an instance of DealsPaging
            //instance = new DealsPaging();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DealsPaging
        /// </summary>
        [Fact]
        public void DealsPagingInstanceTest()
        {
            // TODO uncomment below to test "IsType" DealsPaging
            //Assert.IsType<DealsPaging>(instance);
        }


        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }
        /// <summary>
        /// Test the property 'Prev'
        /// </summary>
        [Fact]
        public void PrevTest()
        {
            // TODO unit test for the property 'Prev'
        }

    }

}
