/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing ExtensionActionDefinitionPatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtensionActionDefinitionPatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtensionActionDefinitionPatch
        //private ExtensionActionDefinitionPatch instance;

        public ExtensionActionDefinitionPatchTests()
        {
            // TODO uncomment below to create an instance of ExtensionActionDefinitionPatch
            //instance = new ExtensionActionDefinitionPatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtensionActionDefinitionPatch
        /// </summary>
        [Fact]
        public void ExtensionActionDefinitionPatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtensionActionDefinitionPatch
            //Assert.IsType<ExtensionActionDefinitionPatch>(instance);
        }


        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            // TODO unit test for the property 'ActionUrl'
        }
        /// <summary>
        /// Test the property 'Published'
        /// </summary>
        [Fact]
        public void PublishedTest()
        {
            // TODO unit test for the property 'Published'
        }
        /// <summary>
        /// Test the property 'InputFields'
        /// </summary>
        [Fact]
        public void InputFieldsTest()
        {
            // TODO unit test for the property 'InputFields'
        }
        /// <summary>
        /// Test the property 'ObjectRequestOptions'
        /// </summary>
        [Fact]
        public void ObjectRequestOptionsTest()
        {
            // TODO unit test for the property 'ObjectRequestOptions'
        }
        /// <summary>
        /// Test the property 'InputFieldDependencies'
        /// </summary>
        [Fact]
        public void InputFieldDependenciesTest()
        {
            // TODO unit test for the property 'InputFieldDependencies'
        }
        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'ObjectTypes'
        /// </summary>
        [Fact]
        public void ObjectTypesTest()
        {
            // TODO unit test for the property 'ObjectTypes'
        }

    }

}
