/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalUnifiedEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalUnifiedEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalUnifiedEvent
        //private ExternalUnifiedEvent instance;

        public ExternalUnifiedEventTests()
        {
            // TODO uncomment below to create an instance of ExternalUnifiedEvent
            //instance = new ExternalUnifiedEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalUnifiedEvent
        /// </summary>
        [Fact]
        public void ExternalUnifiedEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalUnifiedEvent
            //Assert.IsType<ExternalUnifiedEvent>(instance);
        }


        /// <summary>
        /// Test the property 'ObjectType'
        /// </summary>
        [Fact]
        public void ObjectTypeTest()
        {
            // TODO unit test for the property 'ObjectType'
        }
        /// <summary>
        /// Test the property 'ObjectId'
        /// </summary>
        [Fact]
        public void ObjectIdTest()
        {
            // TODO unit test for the property 'ObjectId'
        }
        /// <summary>
        /// Test the property 'EventType'
        /// </summary>
        [Fact]
        public void EventTypeTest()
        {
            // TODO unit test for the property 'EventType'
        }
        /// <summary>
        /// Test the property 'OccurredAt'
        /// </summary>
        [Fact]
        public void OccurredAtTest()
        {
            // TODO unit test for the property 'OccurredAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
