/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceUpdateRequest
        //private InvoiceUpdateRequest instance;

        public InvoiceUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of InvoiceUpdateRequest
            //instance = new InvoiceUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceUpdateRequest
        /// </summary>
        [Fact]
        public void InvoiceUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceUpdateRequest
            //Assert.IsType<InvoiceUpdateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ExternalInvoiceNumber'
        /// </summary>
        [Fact]
        public void ExternalInvoiceNumberTest()
        {
            // TODO unit test for the property 'ExternalInvoiceNumber'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'ExternalRecipientId'
        /// </summary>
        [Fact]
        public void ExternalRecipientIdTest()
        {
            // TODO unit test for the property 'ExternalRecipientId'
        }
        /// <summary>
        /// Test the property 'ReceivedByRecipientDate'
        /// </summary>
        [Fact]
        public void ReceivedByRecipientDateTest()
        {
            // TODO unit test for the property 'ReceivedByRecipientDate'
        }
        /// <summary>
        /// Test the property 'IsVoided'
        /// </summary>
        [Fact]
        public void IsVoidedTest()
        {
            // TODO unit test for the property 'IsVoided'
        }
        /// <summary>
        /// Test the property 'ReceivedByCustomerDate'
        /// </summary>
        [Fact]
        public void ReceivedByCustomerDateTest()
        {
            // TODO unit test for the property 'ReceivedByCustomerDate'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Fact]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }

    }

}
