/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing ObjectTypeDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ObjectTypeDefinitionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ObjectTypeDefinition
        //private ObjectTypeDefinition instance;

        public ObjectTypeDefinitionTests()
        {
            // TODO uncomment below to create an instance of ObjectTypeDefinition
            //instance = new ObjectTypeDefinition();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ObjectTypeDefinition
        /// </summary>
        [Fact]
        public void ObjectTypeDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ObjectTypeDefinition
            //Assert.IsType<ObjectTypeDefinition>(instance);
        }


        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }
        /// <summary>
        /// Test the property 'RequiredProperties'
        /// </summary>
        [Fact]
        public void RequiredPropertiesTest()
        {
            // TODO unit test for the property 'RequiredProperties'
        }
        /// <summary>
        /// Test the property 'SearchableProperties'
        /// </summary>
        [Fact]
        public void SearchablePropertiesTest()
        {
            // TODO unit test for the property 'SearchableProperties'
        }
        /// <summary>
        /// Test the property 'PrimaryDisplayProperty'
        /// </summary>
        [Fact]
        public void PrimaryDisplayPropertyTest()
        {
            // TODO unit test for the property 'PrimaryDisplayProperty'
        }
        /// <summary>
        /// Test the property 'SecondaryDisplayProperties'
        /// </summary>
        [Fact]
        public void SecondaryDisplayPropertiesTest()
        {
            // TODO unit test for the property 'SecondaryDisplayProperties'
        }
        /// <summary>
        /// Test the property 'Archived'
        /// </summary>
        [Fact]
        public void ArchivedTest()
        {
            // TODO unit test for the property 'Archived'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'FullyQualifiedName'
        /// </summary>
        [Fact]
        public void FullyQualifiedNameTest()
        {
            // TODO unit test for the property 'FullyQualifiedName'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'ObjectTypeId'
        /// </summary>
        [Fact]
        public void ObjectTypeIdTest()
        {
            // TODO unit test for the property 'ObjectTypeId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PortalId'
        /// </summary>
        [Fact]
        public void PortalIdTest()
        {
            // TODO unit test for the property 'PortalId'
        }

    }

}
