/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing PublicSubscriptionStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PublicSubscriptionStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PublicSubscriptionStatus
        //private PublicSubscriptionStatus instance;

        public PublicSubscriptionStatusTests()
        {
            // TODO uncomment below to create an instance of PublicSubscriptionStatus
            //instance = new PublicSubscriptionStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PublicSubscriptionStatus
        /// </summary>
        [Fact]
        public void PublicSubscriptionStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" PublicSubscriptionStatus
            //Assert.IsType<PublicSubscriptionStatus>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'SourceOfStatus'
        /// </summary>
        [Fact]
        public void SourceOfStatusTest()
        {
            // TODO unit test for the property 'SourceOfStatus'
        }
        /// <summary>
        /// Test the property 'BrandId'
        /// </summary>
        [Fact]
        public void BrandIdTest()
        {
            // TODO unit test for the property 'BrandId'
        }
        /// <summary>
        /// Test the property 'PreferenceGroupName'
        /// </summary>
        [Fact]
        public void PreferenceGroupNameTest()
        {
            // TODO unit test for the property 'PreferenceGroupName'
        }
        /// <summary>
        /// Test the property 'LegalBasis'
        /// </summary>
        [Fact]
        public void LegalBasisTest()
        {
            // TODO unit test for the property 'LegalBasis'
        }
        /// <summary>
        /// Test the property 'LegalBasisExplanation'
        /// </summary>
        [Fact]
        public void LegalBasisExplanationTest()
        {
            // TODO unit test for the property 'LegalBasisExplanation'
        }

    }

}
