/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing QuotesBatchResponseSimplePublicObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class QuotesBatchResponseSimplePublicObjectTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for QuotesBatchResponseSimplePublicObject
        //private QuotesBatchResponseSimplePublicObject instance;

        public QuotesBatchResponseSimplePublicObjectTests()
        {
            // TODO uncomment below to create an instance of QuotesBatchResponseSimplePublicObject
            //instance = new QuotesBatchResponseSimplePublicObject();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QuotesBatchResponseSimplePublicObject
        /// </summary>
        [Fact]
        public void QuotesBatchResponseSimplePublicObjectInstanceTest()
        {
            // TODO uncomment below to test "IsType" QuotesBatchResponseSimplePublicObject
            //Assert.IsType<QuotesBatchResponseSimplePublicObject>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
        /// <summary>
        /// Test the property 'RequestedAt'
        /// </summary>
        [Fact]
        public void RequestedAtTest()
        {
            // TODO unit test for the property 'RequestedAt'
        }
        /// <summary>
        /// Test the property 'StartedAt'
        /// </summary>
        [Fact]
        public void StartedAtTest()
        {
            // TODO unit test for the property 'StartedAt'
        }
        /// <summary>
        /// Test the property 'CompletedAt'
        /// </summary>
        [Fact]
        public void CompletedAtTest()
        {
            // TODO unit test for the property 'CompletedAt'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
