/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing TimelineEventTemplateUpdateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimelineEventTemplateUpdateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimelineEventTemplateUpdateRequest
        //private TimelineEventTemplateUpdateRequest instance;

        public TimelineEventTemplateUpdateRequestTests()
        {
            // TODO uncomment below to create an instance of TimelineEventTemplateUpdateRequest
            //instance = new TimelineEventTemplateUpdateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimelineEventTemplateUpdateRequest
        /// </summary>
        [Fact]
        public void TimelineEventTemplateUpdateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimelineEventTemplateUpdateRequest
            //Assert.IsType<TimelineEventTemplateUpdateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'HeaderTemplate'
        /// </summary>
        [Fact]
        public void HeaderTemplateTest()
        {
            // TODO unit test for the property 'HeaderTemplate'
        }
        /// <summary>
        /// Test the property 'DetailTemplate'
        /// </summary>
        [Fact]
        public void DetailTemplateTest()
        {
            // TODO unit test for the property 'DetailTemplate'
        }
        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
