/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HubSpot.NET.Api;
using HubSpot.NET.Model;
using HubSpot.NET.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace HubSpot.NET.Test.Model
{
    /// <summary>
    ///  Class for testing TimelineEventIFrame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimelineEventIFrameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimelineEventIFrame
        //private TimelineEventIFrame instance;

        public TimelineEventIFrameTests()
        {
            // TODO uncomment below to create an instance of TimelineEventIFrame
            //instance = new TimelineEventIFrame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimelineEventIFrame
        /// </summary>
        [Fact]
        public void TimelineEventIFrameInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimelineEventIFrame
            //Assert.IsType<TimelineEventIFrame>(instance);
        }


        /// <summary>
        /// Test the property 'LinkLabel'
        /// </summary>
        [Fact]
        public void LinkLabelTest()
        {
            // TODO unit test for the property 'LinkLabel'
        }
        /// <summary>
        /// Test the property 'HeaderLabel'
        /// </summary>
        [Fact]
        public void HeaderLabelTest()
        {
            // TODO unit test for the property 'HeaderLabel'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }

    }

}
