/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using HubSpot.NET.Client;
using HubSpot.NET.Model;

namespace HubSpot.NET.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContentApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete a file
        /// </summary>
        /// <remarks>
        /// Deletes the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns></returns>
        void DeleteCmsV3SourceCodeEnvironmentContentPath(string environment, string path);

        /// <summary>
        /// Delete a file
        /// </summary>
        /// <remarks>
        /// Deletes the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path);
        /// <summary>
        /// Download a file
        /// </summary>
        /// <remarks>
        /// Downloads the byte contents of the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>Error</returns>
        Error GetCmsV3SourceCodeEnvironmentContentPath(string environment, string path);

        /// <summary>
        /// Download a file
        /// </summary>
        /// <remarks>
        /// Downloads the byte contents of the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>ApiResponse of Error</returns>
        ApiResponse<Error> GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path);
        /// <summary>
        /// Create a file
        /// </summary>
        /// <remarks>
        /// Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>AssetFileMetadata</returns>
        [Obsolete]
        AssetFileMetadata PostCmsV3SourceCodeEnvironmentContentPath(string environment, string path, System.IO.Stream file = default(System.IO.Stream));

        /// <summary>
        /// Create a file
        /// </summary>
        /// <remarks>
        /// Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>ApiResponse of AssetFileMetadata</returns>
        [Obsolete]
        ApiResponse<AssetFileMetadata> PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path, System.IO.Stream file = default(System.IO.Stream));
        /// <summary>
        /// Create or update a file
        /// </summary>
        /// <remarks>
        /// Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>AssetFileMetadata</returns>
        AssetFileMetadata PutCmsV3SourceCodeEnvironmentContentPath(string environment, string path, System.IO.Stream file = default(System.IO.Stream));

        /// <summary>
        /// Create or update a file
        /// </summary>
        /// <remarks>
        /// Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>ApiResponse of AssetFileMetadata</returns>
        ApiResponse<AssetFileMetadata> PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path, System.IO.Stream file = default(System.IO.Stream));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContentApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete a file
        /// </summary>
        /// <remarks>
        /// Deletes the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete a file
        /// </summary>
        /// <remarks>
        /// Deletes the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Download a file
        /// </summary>
        /// <remarks>
        /// Downloads the byte contents of the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Error</returns>
        System.Threading.Tasks.Task<Error> GetCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Download a file
        /// </summary>
        /// <remarks>
        /// Downloads the byte contents of the file at the specified path in the specified environment.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Error)</returns>
        System.Threading.Tasks.Task<ApiResponse<Error>> GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create a file
        /// </summary>
        /// <remarks>
        /// Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetFileMetadata</returns>
        [Obsolete]
        System.Threading.Tasks.Task<AssetFileMetadata> PostCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create a file
        /// </summary>
        /// <remarks>
        /// Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetFileMetadata)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<AssetFileMetadata>> PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create or update a file
        /// </summary>
        /// <remarks>
        /// Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetFileMetadata</returns>
        System.Threading.Tasks.Task<AssetFileMetadata> PutCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create or update a file
        /// </summary>
        /// <remarks>
        /// Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetFileMetadata)</returns>
        System.Threading.Tasks.Task<ApiResponse<AssetFileMetadata>> PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContentApi : IContentApiSync, IContentApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContentApi : IContentApi
    {
        private HubSpot.NET.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ContentApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ContentApi(string basePath)
        {
            this.Configuration = HubSpot.NET.Client.Configuration.MergeConfigurations(
                HubSpot.NET.Client.GlobalConfiguration.Instance,
                new HubSpot.NET.Client.Configuration { BasePath = basePath }
            );
            this.Client = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ContentApi(HubSpot.NET.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = HubSpot.NET.Client.Configuration.MergeConfigurations(
                HubSpot.NET.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ContentApi(HubSpot.NET.Client.ISynchronousClient client, HubSpot.NET.Client.IAsynchronousClient asyncClient, HubSpot.NET.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public HubSpot.NET.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public HubSpot.NET.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public HubSpot.NET.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public HubSpot.NET.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete a file Deletes the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns></returns>
        public void DeleteCmsV3SourceCodeEnvironmentContentPath(string environment, string path)
        {
            DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(environment, path);
        }

        /// <summary>
        /// Delete a file Deletes the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public HubSpot.NET.Client.ApiResponse<Object> DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path)
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->DeleteCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->DeleteCmsV3SourceCodeEnvironmentContentPath");
            }

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a file Deletes the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(environment, path, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Delete a file Deletes the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<Object>> DeleteCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->DeleteCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->DeleteCmsV3SourceCodeEnvironmentContentPath");
            }


            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download a file Downloads the byte contents of the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>Error</returns>
        public Error GetCmsV3SourceCodeEnvironmentContentPath(string environment, string path)
        {
            HubSpot.NET.Client.ApiResponse<Error> localVarResponse = GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(environment, path);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download a file Downloads the byte contents of the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <returns>ApiResponse of Error</returns>
        public HubSpot.NET.Client.ApiResponse<Error> GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path)
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->GetCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->GetCmsV3SourceCodeEnvironmentContentPath");
            }

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<Error>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download a file Downloads the byte contents of the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Error</returns>
        public async System.Threading.Tasks.Task<Error> GetCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            HubSpot.NET.Client.ApiResponse<Error> localVarResponse = await GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(environment, path, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download a file Downloads the byte contents of the file at the specified path in the specified environment.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Error)</returns>
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<Error>> GetCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->GetCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->GetCmsV3SourceCodeEnvironmentContentPath");
            }


            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Error>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a file Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>AssetFileMetadata</returns>
        [Obsolete]
        public AssetFileMetadata PostCmsV3SourceCodeEnvironmentContentPath(string environment, string path, System.IO.Stream file = default(System.IO.Stream))
        {
            HubSpot.NET.Client.ApiResponse<AssetFileMetadata> localVarResponse = PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(environment, path, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a file Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>ApiResponse of AssetFileMetadata</returns>
        [Obsolete]
        public HubSpot.NET.Client.ApiResponse<AssetFileMetadata> PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path, System.IO.Stream file = default(System.IO.Stream))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->PostCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->PostCmsV3SourceCodeEnvironmentContentPath");
            }

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request
            var localVarResponse = this.Client.Post<AssetFileMetadata>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a file Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetFileMetadata</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AssetFileMetadata> PostCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            HubSpot.NET.Client.ApiResponse<AssetFileMetadata> localVarResponse = await PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(environment, path, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a file Creates a file at the specified path in the specified environment. Accepts multipart/form-data content type. Throws an error if a file already exists at the specified path.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetFileMetadata)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<AssetFileMetadata>> PostCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->PostCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->PostCmsV3SourceCodeEnvironmentContentPath");
            }


            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AssetFileMetadata>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create or update a file Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>AssetFileMetadata</returns>
        public AssetFileMetadata PutCmsV3SourceCodeEnvironmentContentPath(string environment, string path, System.IO.Stream file = default(System.IO.Stream))
        {
            HubSpot.NET.Client.ApiResponse<AssetFileMetadata> localVarResponse = PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(environment, path, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create or update a file Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <returns>ApiResponse of AssetFileMetadata</returns>
        public HubSpot.NET.Client.ApiResponse<AssetFileMetadata> PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfo(string environment, string path, System.IO.Stream file = default(System.IO.Stream))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->PutCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->PutCmsV3SourceCodeEnvironmentContentPath");
            }

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request
            var localVarResponse = this.Client.Put<AssetFileMetadata>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PutCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create or update a file Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AssetFileMetadata</returns>
        public async System.Threading.Tasks.Task<AssetFileMetadata> PutCmsV3SourceCodeEnvironmentContentPathAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            HubSpot.NET.Client.ApiResponse<AssetFileMetadata> localVarResponse = await PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(environment, path, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create or update a file Upserts a file at the specified path in the specified environment. Accepts multipart/form-data content type.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="environment">The environment of the file (\&quot;draft\&quot; or \&quot;published\&quot;).</param>
        /// <param name="path">The file system location of the file.</param>
        /// <param name="file">The file to upload. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AssetFileMetadata)</returns>
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<AssetFileMetadata>> PutCmsV3SourceCodeEnvironmentContentPathWithHttpInfoAsync(string environment, string path, System.IO.Stream file = default(System.IO.Stream), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'environment' is set
            if (environment == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'environment' when calling ContentApi->PutCmsV3SourceCodeEnvironmentContentPath");
            }

            // verify the required parameter 'path' is set
            if (path == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'path' when calling ContentApi->PutCmsV3SourceCodeEnvironmentContentPath");
            }


            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("environment", HubSpot.NET.Client.ClientUtils.ParameterToString(environment)); // path parameter
            localVarRequestOptions.PathParameters.Add("path", HubSpot.NET.Client.ClientUtils.ParameterToString(path)); // path parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<AssetFileMetadata>("/cms/v3/source-code/{environment}/content/{path}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PutCmsV3SourceCodeEnvironmentContentPath", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
