/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using HubSpot.NET.Client;
using HubSpot.NET.Model;

namespace HubSpot.NET.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get a single domain
        /// </summary>
        /// <remarks>
        /// Returns a single domains with the id specified.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>Domain</returns>
        Domain GetCmsV3DomainsDomainIdGetById(string domainId, bool? archived = default(bool?));

        /// <summary>
        /// Get a single domain
        /// </summary>
        /// <remarks>
        /// Returns a single domains with the id specified.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>ApiResponse of Domain</returns>
        ApiResponse<Domain> GetCmsV3DomainsDomainIdGetByIdWithHttpInfo(string domainId, bool? archived = default(bool?));
        /// <summary>
        /// Get current domains
        /// </summary>
        /// <remarks>
        /// Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>CollectionResponseWithTotalDomain</returns>
        CollectionResponseWithTotalDomain GetCmsV3DomainsGetPage(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?));

        /// <summary>
        /// Get current domains
        /// </summary>
        /// <remarks>
        /// Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>ApiResponse of CollectionResponseWithTotalDomain</returns>
        ApiResponse<CollectionResponseWithTotalDomain> GetCmsV3DomainsGetPageWithHttpInfo(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get a single domain
        /// </summary>
        /// <remarks>
        /// Returns a single domains with the id specified.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Domain</returns>
        System.Threading.Tasks.Task<Domain> GetCmsV3DomainsDomainIdGetByIdAsync(string domainId, bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get a single domain
        /// </summary>
        /// <remarks>
        /// Returns a single domains with the id specified.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Domain)</returns>
        System.Threading.Tasks.Task<ApiResponse<Domain>> GetCmsV3DomainsDomainIdGetByIdWithHttpInfoAsync(string domainId, bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get current domains
        /// </summary>
        /// <remarks>
        /// Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CollectionResponseWithTotalDomain</returns>
        System.Threading.Tasks.Task<CollectionResponseWithTotalDomain> GetCmsV3DomainsGetPageAsync(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get current domains
        /// </summary>
        /// <remarks>
        /// Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </remarks>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CollectionResponseWithTotalDomain)</returns>
        System.Threading.Tasks.Task<ApiResponse<CollectionResponseWithTotalDomain>> GetCmsV3DomainsGetPageWithHttpInfoAsync(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDomainsApi : IDomainsApiSync, IDomainsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DomainsApi : IDomainsApi
    {
        private HubSpot.NET.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DomainsApi(string basePath)
        {
            this.Configuration = HubSpot.NET.Client.Configuration.MergeConfigurations(
                HubSpot.NET.Client.GlobalConfiguration.Instance,
                new HubSpot.NET.Client.Configuration { BasePath = basePath }
            );
            this.Client = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DomainsApi(HubSpot.NET.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = HubSpot.NET.Client.Configuration.MergeConfigurations(
                HubSpot.NET.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new HubSpot.NET.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DomainsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DomainsApi(HubSpot.NET.Client.ISynchronousClient client, HubSpot.NET.Client.IAsynchronousClient asyncClient, HubSpot.NET.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = HubSpot.NET.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public HubSpot.NET.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public HubSpot.NET.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public HubSpot.NET.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public HubSpot.NET.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get a single domain Returns a single domains with the id specified.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>Domain</returns>
        public Domain GetCmsV3DomainsDomainIdGetById(string domainId, bool? archived = default(bool?))
        {
            HubSpot.NET.Client.ApiResponse<Domain> localVarResponse = GetCmsV3DomainsDomainIdGetByIdWithHttpInfo(domainId, archived);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a single domain Returns a single domains with the id specified.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>ApiResponse of Domain</returns>
        public HubSpot.NET.Client.ApiResponse<Domain> GetCmsV3DomainsDomainIdGetByIdWithHttpInfo(string domainId, bool? archived = default(bool?))
        {
            // verify the required parameter 'domainId' is set
            if (domainId == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'domainId' when calling DomainsApi->GetCmsV3DomainsDomainIdGetById");
            }

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("domainId", HubSpot.NET.Client.ClientUtils.ParameterToString(domainId)); // path parameter
            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<Domain>("/cms/v3/domains/{domainId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3DomainsDomainIdGetById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a single domain Returns a single domains with the id specified.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Domain</returns>
        public async System.Threading.Tasks.Task<Domain> GetCmsV3DomainsDomainIdGetByIdAsync(string domainId, bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            HubSpot.NET.Client.ApiResponse<Domain> localVarResponse = await GetCmsV3DomainsDomainIdGetByIdWithHttpInfoAsync(domainId, archived, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a single domain Returns a single domains with the id specified.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="domainId">The unique ID of the domain.</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Domain)</returns>
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<Domain>> GetCmsV3DomainsDomainIdGetByIdWithHttpInfoAsync(string domainId, bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'domainId' is set
            if (domainId == null)
            {
                throw new HubSpot.NET.Client.ApiException(400, "Missing required parameter 'domainId' when calling DomainsApi->GetCmsV3DomainsDomainIdGetById");
            }


            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("domainId", HubSpot.NET.Client.ClientUtils.ParameterToString(domainId)); // path parameter
            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Domain>("/cms/v3/domains/{domainId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3DomainsDomainIdGetById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get current domains Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>CollectionResponseWithTotalDomain</returns>
        public CollectionResponseWithTotalDomain GetCmsV3DomainsGetPage(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?))
        {
            HubSpot.NET.Client.ApiResponse<CollectionResponseWithTotalDomain> localVarResponse = GetCmsV3DomainsGetPageWithHttpInfo(createdAt, createdAfter, createdBefore, updatedAt, updatedAfter, updatedBefore, sort, properties, after, before, limit, archived);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get current domains Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <returns>ApiResponse of CollectionResponseWithTotalDomain</returns>
        public HubSpot.NET.Client.ApiResponse<CollectionResponseWithTotalDomain> GetCmsV3DomainsGetPageWithHttpInfo(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?))
        {
            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (createdAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdAt", createdAt));
            }
            if (createdAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdAfter", createdAfter));
            }
            if (createdBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdBefore", createdBefore));
            }
            if (updatedAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedAt", updatedAt));
            }
            if (updatedAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedAfter", updatedAfter));
            }
            if (updatedBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedBefore", updatedBefore));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("multi", "sort", sort));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("multi", "properties", properties));
            }
            if (after != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "after", after));
            }
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }


            // make the HTTP request
            var localVarResponse = this.Client.Get<CollectionResponseWithTotalDomain>("/cms/v3/domains/", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3DomainsGetPage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get current domains Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CollectionResponseWithTotalDomain</returns>
        public async System.Threading.Tasks.Task<CollectionResponseWithTotalDomain> GetCmsV3DomainsGetPageAsync(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            HubSpot.NET.Client.ApiResponse<CollectionResponseWithTotalDomain> localVarResponse = await GetCmsV3DomainsGetPageWithHttpInfoAsync(createdAt, createdAfter, createdBefore, updatedAt, updatedAfter, updatedBefore, sort, properties, after, before, limit, archived, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get current domains Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.
        /// </summary>
        /// <exception cref="HubSpot.NET.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createdAt">Only return domains created at this date. (optional)</param>
        /// <param name="createdAfter">Only return domains created after this date. (optional)</param>
        /// <param name="createdBefore">Only return domains created before this date. (optional)</param>
        /// <param name="updatedAt">Only return domains updated at this date. (optional)</param>
        /// <param name="updatedAfter">Only return domains updated after this date. (optional)</param>
        /// <param name="updatedBefore">Only return domains updated before this date. (optional)</param>
        /// <param name="sort"> (optional)</param>
        /// <param name="properties"> (optional)</param>
        /// <param name="after">The paging cursor token of the last successfully read resource will be returned as the &#x60;paging.next.after&#x60; JSON property of a paged response containing more results. (optional)</param>
        /// <param name="before"> (optional)</param>
        /// <param name="limit">Maximum number of results per page. (optional)</param>
        /// <param name="archived">Whether to return only results that have been archived. (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CollectionResponseWithTotalDomain)</returns>
        public async System.Threading.Tasks.Task<HubSpot.NET.Client.ApiResponse<CollectionResponseWithTotalDomain>> GetCmsV3DomainsGetPageWithHttpInfoAsync(long? createdAt = default(long?), long? createdAfter = default(long?), long? createdBefore = default(long?), long? updatedAt = default(long?), long? updatedAfter = default(long?), long? updatedBefore = default(long?), List<string> sort = default(List<string>), List<string> properties = default(List<string>), string after = default(string), string before = default(string), int? limit = default(int?), bool? archived = default(bool?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            HubSpot.NET.Client.RequestOptions localVarRequestOptions = new HubSpot.NET.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json",
                "*/*"
            };

            var localVarContentType = HubSpot.NET.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = HubSpot.NET.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (createdAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdAt", createdAt));
            }
            if (createdAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdAfter", createdAfter));
            }
            if (createdBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "createdBefore", createdBefore));
            }
            if (updatedAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedAt", updatedAt));
            }
            if (updatedAfter != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedAfter", updatedAfter));
            }
            if (updatedBefore != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "updatedBefore", updatedBefore));
            }
            if (sort != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("multi", "sort", sort));
            }
            if (properties != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("multi", "properties", properties));
            }
            if (after != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "after", after));
            }
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (archived != null)
            {
                localVarRequestOptions.QueryParameters.Add(HubSpot.NET.Client.ClientUtils.ParameterToMultiMap("", "archived", archived));
            }


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CollectionResponseWithTotalDomain>("/cms/v3/domains/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCmsV3DomainsGetPage", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
