/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using HubSpot.NET.Client;
using HubSpot.NET.Api;
// uncomment below to import models
//using HubSpot.NET.Model;

namespace HubSpot.NET.Test.Api
{
    /// <summary>
    ///  Class for testing AuditLogsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AuditLogsApiTests : IDisposable
    {
        private AuditLogsApi instance;

        public AuditLogsApiTests()
        {
            instance = new AuditLogsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditLogsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AuditLogsApi
            //Assert.IsType<AuditLogsApi>(instance);
        }

        /// <summary>
        /// Test GetCmsV3AuditLogsGetPage
        /// </summary>
        [Fact]
        public void GetCmsV3AuditLogsGetPageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<string> objectId = null;
            //List<string> userId = null;
            //string after = null;
            //string before = null;
            //List<string> sort = null;
            //List<string> eventType = null;
            //int? limit = null;
            //List<string> objectType = null;
            //var response = instance.GetCmsV3AuditLogsGetPage(objectId, userId, after, before, sort, eventType, limit, objectType);
            //Assert.IsType<CollectionResponsePublicAuditLog>(response);
        }
    }
}
