/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HubSpot.NET.Client.OpenAPIDateConverter;

namespace HubSpot.NET.Model
{
    /// <summary>
    /// An option for a field value.
    /// </summary>
    [DataContract(Name = "ActionsOption")]
    public partial class ActionsOption : IEquatable<ActionsOption>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsOption" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ActionsOption() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ActionsOption" /> class.
        /// </summary>
        /// <param name="label">The user-facing label for the option. (required).</param>
        /// <param name="value">The internal value for the option. This is what will be included in the execution request to the &#x60;actionUrl&#x60;. (required).</param>
        /// <param name="displayOrder">displayOrder (required).</param>
        /// <param name="doubleData">doubleData (required).</param>
        /// <param name="hidden">hidden (required).</param>
        /// <param name="description">description (required).</param>
        /// <param name="readOnly">readOnly (required).</param>
        public ActionsOption(string label = default(string), string value = default(string), int displayOrder = default(int), decimal doubleData = default(decimal), bool hidden = default(bool), string description = default(string), bool readOnly = default(bool))
        {
            // to ensure "label" is required (not null)
            if (label == null) {
                throw new ArgumentNullException("label is a required property for ActionsOption and cannot be null");
            }
            this.Label = label;
            // to ensure "value" is required (not null)
            if (value == null) {
                throw new ArgumentNullException("value is a required property for ActionsOption and cannot be null");
            }
            this.Value = value;
            this.DisplayOrder = displayOrder;
            this.DoubleData = doubleData;
            this.Hidden = hidden;
            // to ensure "description" is required (not null)
            if (description == null) {
                throw new ArgumentNullException("description is a required property for ActionsOption and cannot be null");
            }
            this.Description = description;
            this.ReadOnly = readOnly;
        }

        /// <summary>
        /// The user-facing label for the option.
        /// </summary>
        /// <value>The user-facing label for the option.</value>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = false)]
        public string Label { get; set; }

        /// <summary>
        /// The internal value for the option. This is what will be included in the execution request to the &#x60;actionUrl&#x60;.
        /// </summary>
        /// <value>The internal value for the option. This is what will be included in the execution request to the &#x60;actionUrl&#x60;.</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Gets or Sets DisplayOrder
        /// </summary>
        [DataMember(Name = "displayOrder", IsRequired = true, EmitDefaultValue = false)]
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Gets or Sets DoubleData
        /// </summary>
        [DataMember(Name = "doubleData", IsRequired = true, EmitDefaultValue = false)]
        public decimal DoubleData { get; set; }

        /// <summary>
        /// Gets or Sets Hidden
        /// </summary>
        [DataMember(Name = "hidden", IsRequired = true, EmitDefaultValue = true)]
        public bool Hidden { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", IsRequired = true, EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets ReadOnly
        /// </summary>
        [DataMember(Name = "readOnly", IsRequired = true, EmitDefaultValue = true)]
        public bool ReadOnly { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ActionsOption {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  DisplayOrder: ").Append(DisplayOrder).Append("\n");
            sb.Append("  DoubleData: ").Append(DoubleData).Append("\n");
            sb.Append("  Hidden: ").Append(Hidden).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ReadOnly: ").Append(ReadOnly).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ActionsOption);
        }

        /// <summary>
        /// Returns true if ActionsOption instances are equal
        /// </summary>
        /// <param name="input">Instance of ActionsOption to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ActionsOption input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.DisplayOrder == input.DisplayOrder ||
                    this.DisplayOrder.Equals(input.DisplayOrder)
                ) && 
                (
                    this.DoubleData == input.DoubleData ||
                    this.DoubleData.Equals(input.DoubleData)
                ) && 
                (
                    this.Hidden == input.Hidden ||
                    this.Hidden.Equals(input.Hidden)
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.ReadOnly == input.ReadOnly ||
                    this.ReadOnly.Equals(input.ReadOnly)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Label != null)
                {
                    hashCode = (hashCode * 59) + this.Label.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DisplayOrder.GetHashCode();
                hashCode = (hashCode * 59) + this.DoubleData.GetHashCode();
                hashCode = (hashCode * 59) + this.Hidden.GetHashCode();
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ReadOnly.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
