/*
 * HubSpot
 *
 * Provides a way for apps to subscribe to certain change events in HubSpot. Once configured, apps will receive event payloads containing details about the changes at a specified target URL. There can only be one target URL for receiving event notifications per app.
 *
 * The version of the OpenAPI document: v3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = HubSpot.NET.Client.OpenAPIDateConverter;

namespace HubSpot.NET.Model
{
    /// <summary>
    /// An input used to create or replace a pipeline&#39;s definition.
    /// </summary>
    [DataContract(Name = "PipelineInput")]
    public partial class PipelineInput : IEquatable<PipelineInput>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PipelineInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PipelineInput" /> class.
        /// </summary>
        /// <param name="label">A unique label used to organize pipelines in HubSpot&#39;s UI (required).</param>
        /// <param name="displayOrder">The order for displaying this pipeline. If two pipelines have a matching &#x60;displayOrder&#x60;, they will be sorted alphabetically by label. (required).</param>
        /// <param name="stages">Pipeline stage inputs used to create the new or replacement pipeline. (required).</param>
        public PipelineInput(string label = default(string), int displayOrder = default(int), List<PipelineStageInput> stages = default(List<PipelineStageInput>))
        {
            // to ensure "label" is required (not null)
            if (label == null) {
                throw new ArgumentNullException("label is a required property for PipelineInput and cannot be null");
            }
            this.Label = label;
            this.DisplayOrder = displayOrder;
            // to ensure "stages" is required (not null)
            if (stages == null) {
                throw new ArgumentNullException("stages is a required property for PipelineInput and cannot be null");
            }
            this.Stages = stages;
        }

        /// <summary>
        /// A unique label used to organize pipelines in HubSpot&#39;s UI
        /// </summary>
        /// <value>A unique label used to organize pipelines in HubSpot&#39;s UI</value>
        [DataMember(Name = "label", IsRequired = true, EmitDefaultValue = false)]
        public string Label { get; set; }

        /// <summary>
        /// The order for displaying this pipeline. If two pipelines have a matching &#x60;displayOrder&#x60;, they will be sorted alphabetically by label.
        /// </summary>
        /// <value>The order for displaying this pipeline. If two pipelines have a matching &#x60;displayOrder&#x60;, they will be sorted alphabetically by label.</value>
        [DataMember(Name = "displayOrder", IsRequired = true, EmitDefaultValue = false)]
        public int DisplayOrder { get; set; }

        /// <summary>
        /// Pipeline stage inputs used to create the new or replacement pipeline.
        /// </summary>
        /// <value>Pipeline stage inputs used to create the new or replacement pipeline.</value>
        [DataMember(Name = "stages", IsRequired = true, EmitDefaultValue = false)]
        public List<PipelineStageInput> Stages { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PipelineInput {\n");
            sb.Append("  Label: ").Append(Label).Append("\n");
            sb.Append("  DisplayOrder: ").Append(DisplayOrder).Append("\n");
            sb.Append("  Stages: ").Append(Stages).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PipelineInput);
        }

        /// <summary>
        /// Returns true if PipelineInput instances are equal
        /// </summary>
        /// <param name="input">Instance of PipelineInput to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PipelineInput input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Label == input.Label ||
                    (this.Label != null &&
                    this.Label.Equals(input.Label))
                ) && 
                (
                    this.DisplayOrder == input.DisplayOrder ||
                    this.DisplayOrder.Equals(input.DisplayOrder)
                ) && 
                (
                    this.Stages == input.Stages ||
                    this.Stages != null &&
                    input.Stages != null &&
                    this.Stages.SequenceEqual(input.Stages)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Label != null)
                {
                    hashCode = (hashCode * 59) + this.Label.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DisplayOrder.GetHashCode();
                if (this.Stages != null)
                {
                    hashCode = (hashCode * 59) + this.Stages.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
